### ISSUE TITLE
yap 3.5.0 beta4 migration issue.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/yap#333]
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'end_time' in /lib/Database.php:46

Stack trace:
#0 /lib/Database.php(46): PDO->exec('CREATE TABLE `r...')
#1 /endpoints/_includes/migrations.php(25): Database->exec('CREATE TABLE `r...')
#2 /endpoints/_includes/functions.php(7): require_once('...')
#3 /admin/header.php(2): require_once('...')
#4 /admin/index.php(2): require_once('...')
#5 {main}
thrown in /lib/Database.php on line 46
````

**Comment by radius314** [comment]
https://github.com/laravel/ideas/issues/874#issuecomment-343639163

**Comment by radius314** [comment]
fix is in master
