### ISSUE TITLE
Call events not displaying

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/yap#344]
call events are being stored in the database but not displaying in the reports section of ui, this happened after upgrading to 3.5 from 3.4. the call functionality is all working fine still.

seeing the following in our error log. this is happening on sezf and nerna

```
[Sat Dec 07 16:45:24.913398 2019] [php7:notice] [pid 17414] [client 54.236.226.130:44830] https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetServiceBodies
[Sat Dec 07 16:45:25.004394 2019] [php7:notice] [pid 17414] [client 54.236.226.130:44830] https://maps.googleapis.com/maps/api/geocode/json?key=REDACTED&address=30308%2CGA&components=country%3Aus
[Sat Dec 07 16:45:25.559651 2019] [php7:notice] [pid 17141] [client 3.95.164.220:49284] https://maps.googleapis.com/maps/api/timezone/json?key=REDACTED&location=33.7717008,-84.3726049&timestamp=1575755125
[Sat Dec 07 16:45:25.692708 2019] [php7:notice] [pid 17141] [client 3.95.164.220:49284] https://tomato.na-bmlt.org/main_server/client_interface/json/?switcher=GetSearchResults&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_info,location_municipality,location_province,location_street,longitude,latitude,distance_in_miles,distance_in_km&sort_results_by_distance=1&long_val=-84.3726049&lat_val=33.7717008&geo_width=-50&weekdays=7
[Sat Dec 07 16:49:44.419651 2019] [php7:notice] [pid 17628] [client 12.28.238.121:17694] PHP Notice:  Undefined index: CallSid in /var/www/bmlt/zonal-yap/endpoints/status.php on line 8
[Sat Dec 07 16:49:44.419711 2019] [php7:notice] [pid 17628] [client 12.28.238.121:17694] PHP Notice:  Undefined index: Called in /var/www/bmlt/zonal-yap/endpoints/status.php on line 9
[Sat Dec 07 16:49:44.419722 2019] [php7:notice] [pid 17628] [client 12.28.238.121:17694] PHP Notice:  Undefined index: Caller in /var/www/bmlt/zonal-yap/endpoints/status.php on line 10
[Sat Dec 07 16:49:44.419729 2019] [php7:notice] [pid 17628] [client 12.28.238.121:17694] PHP Notice:  Undefined index: CallDuration in /var/www/bmlt/zonal-yap/endpoints/status.php on line 11
[Sat Dec 07 16:49:44.599087 2019] [php7:error] [pid 17628] [client 12.28.238.121:17694] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'callsid' cannot be null in /var/www/bmlt/zonal-yap/lib/Database.php:72
Stack trace:
#0 /var/www/bmlt/zonal-yap/lib/Database.php(72): PDOStatement->execute()
#1 /var/www/bmlt/zonal-yap/endpoints/_includes/functions.php(1894): Database->execute()
#2 /var/www/bmlt/zonal-yap/endpoints/status.php(17): insertCallRecord(Object(CallRecord))
#3 {main}\n  thrown in /var/www/bmlt/zonal-yap/lib/Database.php on line 72
```

for both sites, they initially worked and then stopped.

**Comment by radius314** [comment]
This issue listed above is different than the bug I know about with call events not displaying.

**Comment by radius314** [comment]
Per the logs.

**Comment by radius314** [comment]
This log error is related to the events not showing.   This is related to default limits on `GROUP_CONCAT()`.  This fix for that is in master, however there is a JOIN related issue which needs to be sorted, which is showing duplicate records in the response.

```
[Sat Dec 07 20:17:01.587957 2019] [php7:notice] [pid 17682] [client 12.28.238.121:11988] callEvents issue, referer: https://bmlt.sezf.org/zonal-yap/admin/reports.php
[Sat Dec 07 20:17:01.588003 2019] [php7:warn] [pid 17682] [client 12.28.238.121:11988] PHP Warning:  Invalid argument supplied for foreach() in /var/www/bmlt/zonal-yap/endpoints/_includes/functions.php on line 1941, referer: https://bmlt.sezf.org/zonal-yap/admin/reports.php
```

**Comment by radius314** [comment]
The error you posted is very strange.  I'm not sure how that is even possible.

**Comment by radius314** [comment]
can you try the latest build?

**Comment by pjaudiomv** [comment]
yes thanks, looks good. events records arent sorting properly im guessing because of the timestamps, gonna open ticket.
