### ISSUE TITLE
Skip twilio authentication check, or hide the error, for zonal servers.

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/yap#614]
**Is your feature request related to a problem? Please describe.**
A zonal server typically has no server-wide API key. This results in an error when you log in to Yap.

**Describe the solution you'd like**
I'd like a way to skip this check, or hide the error, for zonal servers.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/10187286/184501009-050b8f3a-8de0-42fc-909f-4557b9a92d91.png">

```{"status":false,"message":"Twilio Rest Error: [HTTP 401] Unable to fetch page: Authenticate","version":"4.1.0","build":"3d0ead3e03575f264f171b941c2bcef0253630d9"}```

**Comment by dgershman** [comment]
will be in yap 4.1.1

**Comment by pjaudiomv** [comment]
the move to having upgrade advisory on home screen seems to have brought this back up, the latest version  is getting a 500 with zonal config now/


```
[2022-10-17 01:14:47] production.ERROR: Undefined global variable $twilioClient (View: /var/www/gyro.sezf.org/zonal-yap-new/resources/views/legacy.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined global variable $twilioClient (View: /var/www/bmlt.sezf.org/zonal-yap-new/resources/views/legacy.blade.php) at /var/www/gyro.sezf.org/zonal-yap-new/legacy/_includes/functions.php:597)
[stacktrace]
```

**Comment by dgershman** [comment]
I’m seeing a google api error on the site

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pjaudiomv** [comment]
just fixed the api key

**Comment by pjaudiomv** [comment]
youll see 500 now, this is full stack trace

```
[previous exception] [object] (ErrorException(code: 0): Undefined global variable $twilioClient at /var/www/gyro.sezf.org/zonal-yap/legacy/_includes/functions.php:597)
[stacktrace]
#0 /var/www/gyro.sezf.org/zonal-yap/legacy/_includes/functions.php(597): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/gyro.sezf.org/zonal-yap/legacy/admin/status_control.php(1): UpgradeAdvisor::getStatus()
#2 /var/www/gyro.sezf.org/zonal-yap/legacy/admin/index.php(46): require_once('...')
#3 /var/www/gyro.sezf.org/zonal-yap/storage/framework/views/e483aff1d500c53cc4d484dd3a6487dd7cfe9d1a.php(2): require('...')
#4 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
#5 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#6 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#7 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#8 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#9 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#10 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#11 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#12 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#13 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()
#14 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()
#15 /var/www/gyro.sezf.org/zonal-yap/app/Http/Controllers/LegacyController.php(28): Illuminate\\Routing\\ResponseFactory->view()
#16 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\LegacyController->index()
#17 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#18 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#19 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#21 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#22 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#24 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#26 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#28 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#30 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#31 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#33 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#35 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#37 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#38 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#39 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#40 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#41 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#42 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#45 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#48 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#50 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#52 /var/www/gyro.sezf.org/zonal-yap/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#54 /var/www/gyro.sezf.org/zonal-yap/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#56 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#58 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#59 /var/www/gyro.sezf.org/zonal-yap/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#60 {main}
"}
```

**Comment by dgershman** [comment]
The site isnt loading , 500 error

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pjaudiomv** [comment]
I know, Im saying theres a regression in latest version that broke the feature on this issue ticket. The zonal server is unable to upgrade to latest version at this time.
